## Models Application 

Models: 
1. Naive Bayes (Gaussian & Multinominal) 
2. Logistic Regression
3. KNN
4. Stochastic Gradient Descent
5. SVM (Linear, Poly, Quadratic, RBF)
6. Decision Tree Classifier
7. Decision Tree Bagging
8. Decision Tree Adaboost
9. Random Forest
10. Vote Classification 

Approaches: 

* 70% Training and 30% Testing split 
* Cross Validation with 10 folds 

Metrics: 

* Accuracy Scores (Traing and Test)
* Mean Accuracy Scores - Cross Validation
* AUC Scores
* Confusion Matrix 


In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.metrics import roc_auc_score
from sklearn.metrics import classification_report, confusion_matrix
from sklearn.metrics import accuracy_score
from sklearn.model_selection import KFold
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import cross_val_score
from sklearn.naive_bayes import GaussianNB
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import StandardScaler
from sklearn.naive_bayes import MultinomialNB
from sklearn.neighbors import KNeighborsClassifier
from sklearn.linear_model import SGDClassifier
from sklearn import svm
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn.ensemble import AdaBoostClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.ensemble import VotingClassifier
from sklearn.model_selection import RandomizedSearchCV
from sklearn.ensemble import RandomForestRegressor

In [2]:
# Read Features selected
 
dataset = pd.read_csv(r'C:\Users\cinti\Documents\PythonF\Final_Project_ML\bidders_features_selected.csv')
dataset

bidder_id  total_bids      min_time  \
0     91a3c57b13234af24875c56fb7e2b2f4rb56a          24  9.759490e+15   
1     624f258b49e77713fc34034560f93fb3hu3jo           3  9.764050e+15   
2     1c5f4fc669099bfbfac515cd26997bd12ruaj           4  9.765400e+15   
3     4ab12bc61c82ddd9c2d65e60555808acqgos1         155  9.759250e+15   
4     7eaefc97fbf6af12e930528151f86eb91bafh           1  9.761130e+15   
...                                     ...         ...           ...   
1411  9744d8ea513490911a671959c4a530d81fj5e         248  9.759270e+15   
1412  2baa5a9ec317cb21a11d83f6dc72a2d6xy9jb          11  9.759280e+15   
1413  65d8228c6c1e5b6042f397afed8a5c7cbo6x3         149  9.759290e+15   
1414  c806dbb2decba0ed3c4ff5e2e60a74c2wjvbl           2  9.762800e+15   
1415  84a769adc98498f52debfe57b93a0789556f4           2  9.770760e+15   

          max_time    total_time  average_time  total_auction per user  \
0     9.772620e+15  2.343870e+17  9.766130e+15                      18   
1     9.770510e+15  2.930060e+16  9.766870e+15                       1   
2     9.772540e+15  3.907760e+16  9.769390e+15                       4   
3     9.771230e+15  1.513130e+18  9.762120e+15                      23   
4     9.761130e+15  9.761130e+15  9.761130e+15                       1   
...            ...           ...           ...                     ...   
1411  9.772850e+15  2.421780e+18  9.765240e+15                      91   
1412  9.771590e+15  1.074190e+17  9.765370e+15                       2   
1413  9.771980e+15  1.455300e+18  9.767110e+15                      64   
1414  9.772600e+15  1.953540e+16  9.767700e+15                       1   
1415  9.770760e+15  1.954150e+16  9.770760e+15                       1   

      mean_bids_per_auctions  mean_time_auction  total_country  number_ip  \
0                   1.333333       5.425630e+14              6         20   
1                   3.000000       9.766870e+15              1          3   
2                   1.000000       2.442350e+15              1          4   
3                   6.739130       4.244400e+14              2        123   
4                   1.000000       9.761130e+15              1          1   
...                      ...                ...            ...        ...   
1411                2.725275       1.073100e+14             13         92   
1412                5.500000       4.882680e+15              2         11   
1413                2.328125       1.526110e+14             23         93   
1414                2.000000       9.767700e+15              1          2   
1415                2.000000       9.770760e+15              1          1   

      mean_ips_per_auction  number_url  number_devices  computers  jewelry  \
0                 1.111111           1              14          0        0   
1                 3.000000           2               2          0        0   
2                 1.000000           2               2          0        0   
3                 5.347826          91              53          0        0   
4                 1.000000           1               1          0        0   
...                    ...         ...             ...        ...      ...   
1411              1.010989          80              72          0        1   
1412              5.500000          11               7          0        0   
1413              1.453125          97              61          0        0   
1414              2.000000           1               2          0        0   
1415              1.000000           1               1          0        1   

      outcome  
0           0  
1           0  
2           0  
3           0  
4           0  
...       ...  
1411        0  
1412        0  
1413        0  
1414        0  
1415        0  

[1416 rows x 17 columns]

In [3]:
# Features X Outcome y

X = dataset.iloc[:,:-1]
X = X.drop(columns=['bidder_id'])
y = dataset.iloc[:,-1:]

print(X)
print(y)

      total_bids      min_time      max_time    total_time  average_time  \
0             24  9.759490e+15  9.772620e+15  2.343870e+17  9.766130e+15   
1              3  9.764050e+15  9.770510e+15  2.930060e+16  9.766870e+15   
2              4  9.765400e+15  9.772540e+15  3.907760e+16  9.769390e+15   
3            155  9.759250e+15  9.771230e+15  1.513130e+18  9.762120e+15   
4              1  9.761130e+15  9.761130e+15  9.761130e+15  9.761130e+15   
...          ...           ...           ...           ...           ...   
1411         248  9.759270e+15  9.772850e+15  2.421780e+18  9.765240e+15   
1412          11  9.759280e+15  9.771590e+15  1.074190e+17  9.765370e+15   
1413         149  9.759290e+15  9.771980e+15  1.455300e+18  9.767110e+15   
1414           2  9.762800e+15  9.772600e+15  1.953540e+16  9.767700e+15   
1415           2  9.770760e+15  9.770760e+15  1.954150e+16  9.770760e+15   

      total_auction per user  mean_bids_per_auctions  mean_time_auction  \
0           

In [4]:
# Some models need standardized values to perform better 
sc = StandardScaler()
X_st = sc.fit_transform(X)
X_st 

array([[-0.11384323,  0.7605989 ,  0.82520858, ..., -0.31050702,
        -0.14203137, -0.50088261],
       [-0.11717979,  0.83296322,  0.79376181, ..., -0.39576412,
        -0.14203137, -0.50088261],
       [-0.1170209 ,  0.85438686,  0.82401628, ..., -0.39576412,
        -0.14203137, -0.50088261],
       ...,
       [-0.09398276,  0.75742503,  0.81567022, ...,  0.0234166 ,
        -0.14203137, -0.50088261],
       [-0.11733867,  0.81312651,  0.8249105 , ..., -0.39576412,
        -0.14203137, -0.50088261],
       [-0.11733867,  0.93944667,  0.79748773, ..., -0.40286888,
        -0.14203137,  1.99647577]])

In [5]:
# Split dataset into training and test 70% training and 30% test
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3)

In [6]:
#create an empty dictionary to keep the score of all models 

dict_scores  = {}
dict_scores_auc  = {}

1. Naive Bayes : 

    Gaussian & Multinomial 

In [7]:
# Gaussian:

print('Gaussian Bayes Gaussian\n')

gnb = GaussianNB()

# Train the model using the training sets
gnb.fit(X_train, np.ravel(y_train))

# Predict the response for test dataset
y_pred = gnb.predict(X_test)

# Accuracy: 
print('=== Results ====\n')
print('Using the 70% training, 30% test split:')
print('Accuracy score on test: ' + str(gnb.score(X_test, y_test)))
print('Accuracy score on train: '+ str(gnb.score(X_train, y_train)))

# Using cross-validation:

cv_score = cross_val_score(gnb, X, np.ravel(y), cv=10, scoring='roc_auc')

# Results AUC 

print('\n=== Confusion Matrix ===')
print(confusion_matrix(y_test, y_pred))
print('\n')
print('=== Classification Report ===')
print(classification_report(y_test, y_pred))
print('\n')
print('=== All AUC Scores ===')
print(cv_score)
print('\n')
print('=== Mean AUC Score ===')
print('Mean AUC Score - Gaussian: ', cv_score.mean())

dict_scores_auc['gnb'] = cv_score.mean() 

# Results Accuracy 
cv_score = cross_val_score(gnb, X, np.ravel(y), cv=10, scoring='accuracy')

print('\n=== All Accuracy Scores ===')
print(cv_score)
print('\n')
print('=== Mean Accuracy Score ===')
print('Mean Accuracy Score - Gaussian: ', cv_score.mean())

dict_scores['gnb'] = cv_score.mean() 


Gaussian Bayes Gaussian

=== Results ====

Using the 70% training, 30% test split:
Accuracy score on test: 0.9247058823529412
Accuracy score on train: 0.9434914228052472

=== Confusion Matrix ===
[[393   0]
 [ 32   0]]


=== Classification Report ===
              precision    recall  f1-score   support

           0       0.92      1.00      0.96       393
           1       0.00      0.00      0.00        32

    accuracy                           0.92       425
   macro avg       0.46      0.50      0.48       425
weighted avg       0.86      0.92      0.89       425



=== All AUC Scores ===
[0.66583124 0.69005848 0.64745196 0.79699248 0.73600668 0.60233918
 0.81766917 0.68890977 0.62121212 0.76936027]


=== Mean AUC Score ===
Mean AUC Score - Gaussian:  0.7035831371357687

=== All Accuracy Scores ===
[0.93661972 0.93661972 0.93661972 0.93661972 0.93661972 0.93661972
 0.94326241 0.94326241 0.93617021 0.90780142]


=== Mean Accuracy Score ===
Mean Accuracy Score - Gaussian:  0.93502

c:\users\cinti\appdata\local\programs\python\python38\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [8]:
# Multinominal:

print('Naive Bayes Multinominal\n')

mnb = MultinomialNB().fit(X_train, np.ravel(y_train))

# Train the model using the training sets
mnb.fit(X_train, np.ravel(y_train))

# Predict the response for test dataset
y_pred = mnb.predict(X_test)

# Accuracy: 
print('=== Results ====\n')
print('Using the 70% training, 30% test split:')
print('Accuracy score on test: ' + str(mnb.score(X_test, y_test)))
print('Accuracy score on train: '+ str(mnb.score(X_train, y_train)))

# Using cross-validation:

cv_score = cross_val_score(mnb, X, np.ravel(y), cv=10, scoring='roc_auc')

# Results AUC 

print('\n=== Confusion Matrix ===')
print(confusion_matrix(y_test, y_pred))
print('\n')
print('=== Classification Report ===')
print(classification_report(y_test, y_pred))
print('\n')
print('=== All AUC Scores ===')
print(cv_score)
print('\n')
print('=== Mean AUC Score ===')
print('Mean AUC Score - Multinominal: ', cv_score.mean())

dict_scores_auc['mnb'] = cv_score.mean() 

# Results Accuracy 
cv_score = cross_val_score(mnb, X, np.ravel(y), cv=10, scoring='accuracy')

print('\n=== All Accuracy Scores ===')
print(cv_score)
print('\n')
print('=== Mean Accuracy Score ===')
print('Mean Accuracy Score - Multinominal: ', cv_score.mean())

dict_scores['mbn'] = cv_score.mean() 

Naive Bayes Multinominal

=== Results ====

Using the 70% training, 30% test split:
Accuracy score on test: 0.8705882352941177
Accuracy score on train: 0.8678102926337034

=== Confusion Matrix ===
[[360  33]
 [ 22  10]]


=== Classification Report ===
              precision    recall  f1-score   support

           0       0.94      0.92      0.93       393
           1       0.23      0.31      0.27        32

    accuracy                           0.87       425
   macro avg       0.59      0.61      0.60       425
weighted avg       0.89      0.87      0.88       425



=== All AUC Scores ===
[0.51796157 0.55096074 0.59231412 0.63283208 0.46992481 0.58103592
 0.51738722 0.63862782 0.74368687 0.66540404]


=== Mean AUC Score ===
Mean AUC Score - Multinominal:  0.5910135186450975

=== All Accuracy Scores ===
[0.87323944 0.83802817 0.91549296 0.8943662  0.88028169 0.8943662
 0.86524823 0.87234043 0.90780142 0.85815603]


=== Mean Accuracy Score ===
Mean Accuracy Score - Multinominal: 

2. Logistic Regression

In [9]:
# Logistic Regression

print('Logistic Regression\n')

lr = LogisticRegression()

lr.fit(X_train, np.ravel(y_train))

y_pred = lr.predict(X_test)

# Accuracy: 
print('=== Results ====\n')
print('Using the 70% training, 30% test split:')
print('Accuracy score on test: ' + str(lr.score(X_test, y_test)))
print('Accuracy score on train: '+ str(lr.score(X_train, y_train)))

# Using cross-validation:

cv_score = cross_val_score(lr, X, np.ravel(y), cv=10, scoring='roc_auc')

# Results AUC 

print('\n=== Confusion Matrix ===')
print(confusion_matrix(y_test, y_pred))
print('\n')
print('=== Classification Report ===')
print(classification_report(y_test, y_pred))
print('\n')
print('=== All AUC Scores ===')
print(cv_score)
print('\n')
print('=== Mean AUC Score ===')
print('Mean AUC Score - Logistic Regression: ', cv_score.mean())

dict_scores_auc['lr'] = cv_score.mean() 

# Results Accuracy 
cv_score = cross_val_score(lr, X, np.ravel(y), cv=10, scoring='accuracy')

print('\n=== All Accuracy Scores ===')
print(cv_score)
print('\n')
print('=== Mean Accuracy Score ===')
print('Mean Accuracy Score - Logistic Regression: ', cv_score.mean())

dict_scores['lg'] = cv_score.mean() 

Logistic Regression

=== Results ====

Using the 70% training, 30% test split:
Accuracy score on test: 0.9247058823529412
Accuracy score on train: 0.9434914228052472


c:\users\cinti\appdata\local\programs\python\python38\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=2):
ABNORMAL_TERMINATION_IN_LNSRCH.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\users\cinti\appdata\local\programs\python\python38\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=2):
ABNORMAL_TERMINATION_IN_LNSRCH.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.ht


=== Confusion Matrix ===
[[393   0]
 [ 32   0]]


=== Classification Report ===
              precision    recall  f1-score   support

           0       0.92      1.00      0.96       393
           1       0.00      0.00      0.00        32

    accuracy                           0.92       425
   macro avg       0.46      0.50      0.48       425
weighted avg       0.86      0.92      0.89       425



=== All AUC Scores ===
[0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5 0.5]


=== Mean AUC Score ===
Mean AUC Score - Logistic Regression:  0.5

=== All Accuracy Scores ===
[0.93661972 0.93661972 0.93661972 0.93661972 0.93661972 0.93661972
 0.94326241 0.94326241 0.93617021 0.93617021]


=== Mean Accuracy Score ===
Mean Accuracy Score - Logistic Regression:  0.9378583558086107


3. KNN

In [10]:
# KNN:

print('KNN\n')

knn = KNeighborsClassifier(n_neighbors = 15)

# Train the model using the training sets
knn.fit(X_train, np.ravel(y_train))

# Predict the response for test dataset
y_pred = knn.predict(X_test)


# Accuracy: 
print('=== Results ====\n')
print('Using the 70% training, 30% test split:')
print('Accuracy score on test: ' + str(knn.score(X_test, y_test)))
print('Accuracy score on train: '+ str(knn.score(X_train, y_train)))

# Using cross-validation:

cv_score = cross_val_score(knn, X, np.ravel(y), cv=10, scoring='roc_auc')

# Results AUC 

print('\n=== Confusion Matrix ===')
print(confusion_matrix(y_test, y_pred))
print('\n')
print('=== Classification Report ===')
print(classification_report(y_test, y_pred))
print('\n')
print('=== All AUC Scores ===')
print(cv_score)
print('\n')
print('=== Mean AUC Score ===')
print('Mean AUC Score - KNN: ', cv_score.mean())

dict_scores_auc['knn'] = cv_score.mean() 

# Results Accuracy 
cv_score = cross_val_score(knn, X, np.ravel(y), cv=10, scoring='accuracy')

print('\n=== All Accuracy Scores ===')
print(cv_score)
print('\n')
print('=== Mean Accuracy Score ===')
print('Mean Accuracy Score - KNN: ', cv_score.mean())

dict_scores['knn'] = cv_score.mean() 

KNN

=== Results ====

Using the 70% training, 30% test split:
Accuracy score on test: 0.9247058823529412
Accuracy score on train: 0.9434914228052472

=== Confusion Matrix ===
[[393   0]
 [ 32   0]]


=== Classification Report ===
              precision    recall  f1-score   support

           0       0.92      1.00      0.96       393
           1       0.00      0.00      0.00        32

    accuracy                           0.92       425
   macro avg       0.46      0.50      0.48       425
weighted avg       0.86      0.92      0.89       425



=== All AUC Scores ===
[0.68003342 0.63450292 0.60944027 0.71804511 0.78320802 0.62030075
 0.71475564 0.91071429 0.83796296 0.77104377]


=== Mean AUC Score ===
Mean AUC Score - KNN:  0.7280007151717678

=== All Accuracy Scores ===
[0.93661972 0.93661972 0.93661972 0.93661972 0.93661972 0.93661972
 0.94326241 0.94326241 0.93617021 0.93617021]


=== Mean Accuracy Score ===
Mean Accuracy Score - KNN:  0.9378583558086107


c:\users\cinti\appdata\local\programs\python\python38\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


4. Stochastic Gradient Descent

In [11]:
# Stochastic Gradient Descent

print('Stochastic Gradient Descent\n')

sgd = SGDClassifier(loss = 'modified_huber', shuffle = True, random_state=101)

sgd.fit(X_train, np.ravel(y_train))

y_pred = sgd.predict(X_test)

# Accuracy: 
print('=== Results ====\n')
print('Using the 70% training, 30% test split:')
print('Accuracy score on test: ' + str(sgd.score(X_test, y_test)))
print('Accuracy score on train: '+ str(sgd.score(X_train, y_train)))

# Using cross-validation:

cv_score = cross_val_score(sgd, X, np.ravel(y), cv=10, scoring='roc_auc')

# Results AUC 

print('\n=== Confusion Matrix ===')
print(confusion_matrix(y_test, y_pred))
print('\n')
print('=== Classification Report ===')
print(classification_report(y_test, y_pred))
print('\n')
print('=== All AUC Scores ===')
print(cv_score)
print('\n')
print('=== Mean AUC Score ===')
print('Mean AUC Score - SGD: ', cv_score.mean())

dict_scores_auc['sgd'] = cv_score.mean() 


# Results Accuracy 
cv_score = cross_val_score(sgd, X, np.ravel(y), cv=10, scoring='accuracy')

print('\n=== All Accuracy Scores ===')
print(cv_score)
print('\n')
print('=== Mean Accuracy Score ===')
print('Mean Accuracy Score - SGD: ', cv_score.mean())

dict_scores['sgd'] = cv_score.mean() 

Stochastic Gradient Descent

=== Results ====

Using the 70% training, 30% test split:
Accuracy score on test: 0.9247058823529412
Accuracy score on train: 0.9434914228052472

=== Confusion Matrix ===
[[393   0]
 [ 32   0]]


=== Classification Report ===
              precision    recall  f1-score   support

           0       0.92      1.00      0.96       393
           1       0.00      0.00      0.00        32

    accuracy                           0.92       425
   macro avg       0.46      0.50      0.48       425
weighted avg       0.86      0.92      0.89       425



=== All AUC Scores ===
[0.32080201 0.72180451 0.31161236 0.84294069 0.2406015  0.16457811
 0.21240602 0.12593985 0.09343434 0.1952862 ]


=== Mean AUC Score ===
Mean AUC Score - SGD:  0.3229405584668742

=== All Accuracy Scores ===
[0.93661972 0.06338028 0.93661972 0.06338028 0.93661972 0.93661972
 0.94326241 0.94326241 0.93617021 0.93617021]


=== Mean Accuracy Score ===
Mean Accuracy Score - SGD:  0.76321046848

c:\users\cinti\appdata\local\programs\python\python38\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


5. SVM 

In [12]:
#Linear SVM 

print('Linear SVM \n')

X_st_train, X_st_test, y_train, y_test = train_test_split(X_st, y, test_size=0.3)

svm_linear = svm.SVC(kernel='linear')
svm_linear.fit(X_st_train, np.ravel(y_train))
y_pred = svm_linear.predict(X_st_test)

# Accuracy: 
print('=== Results ====\n')
print('Using the 70% training, 30% test split:')
print('Accuracy score on test: ' + str(svm_linear.score(X_st_test, y_test)))
print('Accuracy score on train: '+ str(svm_linear.score(X_st_train, y_train)))

# Using cross-validation:

cv_score = cross_val_score(svm_linear, X_st, np.ravel(y), cv=10, scoring='roc_auc')

# Results AUC 

print('\n=== Confusion Matrix ===')
print(confusion_matrix(y_test, y_pred))
print('\n')
print('=== Classification Report ===')
print(classification_report(y_test, y_pred))
print('\n')
print('=== All AUC Scores ===')
print(cv_score)
print('\n')
print('=== Mean AUC Score ===')
print('Mean AUC Score - SVM Linear: ', cv_score.mean())

dict_scores_auc['svm_linear'] = cv_score.mean() 

# Results Accuracy 
cv_score = cross_val_score(svm_linear, X_st, np.ravel(y), cv=10, scoring='accuracy')

print('\n=== All Accuracy Scores ===')
print(cv_score)
print('\n')
print('=== Mean Accuracy Score ===')
print('Mean Accuracy Score - SVM Linear: ', cv_score.mean())

dict_scores['svm_linear'] = cv_score.mean() 

Linear SVM 

=== Results ====

Using the 70% training, 30% test split:
Accuracy score on test: 0.9317647058823529
Accuracy score on train: 0.9404641775983855

=== Confusion Matrix ===
[[396   0]
 [ 29   0]]


=== Classification Report ===
              precision    recall  f1-score   support

           0       0.93      1.00      0.96       396
           1       0.00      0.00      0.00        29

    accuracy                           0.93       425
   macro avg       0.47      0.50      0.48       425
weighted avg       0.87      0.93      0.90       425



=== All AUC Scores ===
[0.49206349 0.52213868 0.55304929 0.58061821 0.59398496 0.57811195
 0.3787594  0.43421053 0.77861953 0.55387205]


=== Mean AUC Score ===
Mean AUC Score - SVM Linear:  0.546542809042809

=== All Accuracy Scores ===
[0.93661972 0.93661972 0.93661972 0.93661972 0.93661972 0.93661972
 0.94326241 0.94326241 0.93617021 0.93617021]


=== Mean Accuracy Score ===
Mean Accuracy Score - SVM Linear:  0.93785835580861

c:\users\cinti\appdata\local\programs\python\python38\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [13]:
# Poly

print('Poly SVM \n')
svm_poly = svm.SVC(kernel='poly')
svm_poly.fit(X_st_train, np.ravel(y_train))
y_pred = svm_poly.predict(X_st_test)

# Accuracy: 
print('=== Results ====\n')
print('Using the 70% training, 30% test split:')
print('Accuracy score on test: ' + str(svm_poly.score(X_st_test, y_test)))
print('Accuracy score on train: '+ str(svm_poly.score(X_st_train, y_train)))

# Using cross-validation:

cv_score = cross_val_score(svm_poly, X_st, np.ravel(y), cv=10, scoring='roc_auc')

# Results AUC 

print('\n=== Confusion Matrix ===')
print(confusion_matrix(y_test, y_pred))
print('\n')
print('=== Classification Report ===')
print(classification_report(y_test, y_pred))
print('\n')
print('=== All AUC Scores ===')
print(cv_score)
print('\n')
print('=== Mean AUC Score ===')
print('Mean AUC Score - SVM Poly: ', cv_score.mean())

dict_scores_auc['svm_poly'] = cv_score.mean() 

# Results Accuracy 
cv_score = cross_val_score(svm_poly, X_st, np.ravel(y), cv=10, scoring='accuracy')

print('\n=== All Accuracy Scores ===')
print(cv_score)
print('\n')
print('=== Mean Accuracy Score ===')
print('Mean Accuracy Score - SVM Poly: ', cv_score.mean())

dict_scores['svm_poly'] = cv_score.mean() 


Poly SVM 

=== Results ====

Using the 70% training, 30% test split:
Accuracy score on test: 0.9317647058823529
Accuracy score on train: 0.9475277497477296

=== Confusion Matrix ===
[[395   1]
 [ 28   1]]


=== Classification Report ===
              precision    recall  f1-score   support

           0       0.93      1.00      0.96       396
           1       0.50      0.03      0.06        29

    accuracy                           0.93       425
   macro avg       0.72      0.52      0.51       425
weighted avg       0.90      0.93      0.90       425



=== All AUC Scores ===
[0.63993317 0.68253968 0.73767753 0.61319967 0.55137845 0.56307435
 0.54699248 0.65225564 0.72979798 0.69107744]


=== Mean AUC Score ===
Mean AUC Score - SVM Poly:  0.6407926381610592

=== All Accuracy Scores ===
[0.93661972 0.94366197 0.93661972 0.93661972 0.93661972 0.93661972
 0.92907801 0.95035461 0.95035461 0.94326241]


=== Mean Accuracy Score ===
Mean Accuracy Score - SVM Poly:  0.9399810208770353


In [14]:
# Quadratic

print('Quadratic SVM \n')

svm_poly = svm.SVC(kernel='poly', degree=2)

svm_poly.fit(X_st_train, np.ravel(y_train))

y_pred = svm_poly.predict(X_st_test)

# Accuracy: 
print('=== Results ====\n')
print('Using the 70% training, 30% test split:')
print('Accuracy score on test: ' + str(svm_poly.score(X_st_test, y_test)))
print('Accuracy score on train: '+ str(svm_poly.score(X_st_train, y_train)))

# Using cross-validation:

cv_score = cross_val_score(svm_poly, X_st, np.ravel(y), cv=10, scoring='roc_auc')

# Results AUC 

print('\n=== Confusion Matrix ===')
print(confusion_matrix(y_test, y_pred))
print('\n')
print('=== Classification Report ===')
print(classification_report(y_test, y_pred))
print('\n')
print('=== All AUC Scores ===')
print(cv_score)
print('\n')
print('=== Mean AUC Score ===')
print('Mean AUC Score - SVM Quadratic: ', cv_score.mean())

dict_scores_auc['svm_quadratic'] = cv_score.mean() 

# Results Accuracy 
cv_score = cross_val_score(svm_poly, X_st, np.ravel(y), cv=10, scoring='accuracy')

print('\n=== All Accuracy Scores ===')
print(cv_score)
print('\n')
print('=== Mean Accuracy Score ===')
print('Mean Accuracy Score - SVM Quadratic: ', cv_score.mean())

dict_scores['svm_quadratic'] = cv_score.mean() 

Quadratic SVM 

=== Results ====

Using the 70% training, 30% test split:
Accuracy score on test: 0.9317647058823529
Accuracy score on train: 0.9445005045408678

=== Confusion Matrix ===
[[396   0]
 [ 29   0]]


=== Classification Report ===
              precision    recall  f1-score   support

           0       0.93      1.00      0.96       396
           1       0.00      0.00      0.00        29

    accuracy                           0.93       425
   macro avg       0.47      0.50      0.48       425
weighted avg       0.87      0.93      0.90       425



=== All AUC Scores ===
[0.66917293 0.6716792  0.56892231 0.48120301 0.44026734 0.48203843
 0.31954887 0.63909774 0.76851852 0.62794613]


=== Mean AUC Score ===
Mean AUC Score - SVM Quadratic:  0.566839447102605

=== All Accuracy Scores ===
[0.93661972 0.93661972 0.93661972 0.93661972 0.93661972 0.93661972
 0.93617021 0.94326241 0.93617021 0.93617021]


=== Mean Accuracy Score ===
Mean Accuracy Score - SVM Quadratic:  0.93714

c:\users\cinti\appdata\local\programs\python\python38\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [15]:
#RBF

print('RBF SVM \n')

svm_rbf = svm.SVC(kernel='rbf')

svm_rbf.fit(X_st_train, np.ravel(y_train))

y_pred = svm_rbf.predict(X_st_test)

# Accuracy: 
print('=== Results ====\n')
print('Using the 70% training, 30% test split:')
print('Accuracy score on test: ' + str(svm_rbf.score(X_st_test, y_test)))
print('Accuracy score on train: '+ str(svm_rbf.score(X_st_train, y_train)))

# Using cross-validation:

cv_score = cross_val_score(svm_rbf, X_st, np.ravel(y), cv=10, scoring='roc_auc')

# Results AUC 

print('\n=== Confusion Matrix ===')
print(confusion_matrix(y_test, y_pred))
print('\n')
print('=== Classification Report ===')
print(classification_report(y_test, y_pred))
print('\n')
print('=== All AUC Scores ===')
print(cv_score)
print('\n')
print('=== Mean AUC Score ===')
print('Mean AUC Score - SVM RBF: ', cv_score.mean())

dict_scores_auc['svm_rbf'] = cv_score.mean() 

# Results Accuracy 
cv_score = cross_val_score(svm_rbf, X_st, np.ravel(y), cv=10, scoring='accuracy')

print('\n=== All Accuracy Scores ===')
print(cv_score)
print('\n')
print('=== Mean Accuracy Score ===')
print('Mean Accuracy Score - SVM RBF: ', cv_score.mean())

dict_scores['svm_RBF'] = cv_score.mean() 


RBF SVM 

=== Results ====

Using the 70% training, 30% test split:
Accuracy score on test: 0.9317647058823529
Accuracy score on train: 0.9434914228052472

=== Confusion Matrix ===
[[396   0]
 [ 29   0]]


=== Classification Report ===
              precision    recall  f1-score   support

           0       0.93      1.00      0.96       396
           1       0.00      0.00      0.00        29

    accuracy                           0.93       425
   macro avg       0.47      0.50      0.48       425
weighted avg       0.87      0.93      0.90       425



=== All AUC Scores ===
[0.83040936 0.78362573 0.73099415 0.68504595 0.6908939  0.82790309
 0.7537594  0.70582707 0.89225589 0.79040404]


=== Mean AUC Score ===
Mean AUC Score - SVM RBF:  0.7691118579276475


c:\users\cinti\appdata\local\programs\python\python38\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))



=== All Accuracy Scores ===
[0.93661972 0.93661972 0.93661972 0.93661972 0.93661972 0.93661972
 0.94326241 0.94326241 0.93617021 0.93617021]


=== Mean Accuracy Score ===
Mean Accuracy Score - SVM RBF:  0.9378583558086107


6. Decision Tree Classifier

In [16]:
# Decision Tree
print('Decision Tree Classifier \n')

dt = DecisionTreeClassifier()

dt.fit(X_train, np.ravel(y_train))

y_pred = dt.predict(X_test)

# Accuracy: 
print('=== Results ====\n')
print('Using the 70% training, 30% test split:')
print('Accuracy score on test: ' + str(dt.score(X_test, y_test)))
print('Accuracy score on train: '+ str(dt.score(X_train, y_train)))

# Using cross-validation:

cv_score = cross_val_score(dt, X, np.ravel(y), cv=10, scoring='roc_auc')

# Results AUC 

print('\n=== Confusion Matrix ===')
print(confusion_matrix(y_test, y_pred))
print('\n')
print('=== Classification Report ===')
print(classification_report(y_test, y_pred))
print('\n')
print('=== All AUC Scores ===')
print(cv_score)
print('\n')
print('=== Mean AUC Score ===')
print('Mean AUC Score - Decision Tree: ', cv_score.mean())

dict_scores_auc['dt'] = cv_score.mean() 

# Results Accuracy 
cv_score = cross_val_score(dt, X, np.ravel(y), cv=10, scoring='accuracy')

print('\n=== All Accuracy Scores ===')
print(cv_score)
print('\n')
print('=== Mean Accuracy Score ===')
print('Mean Accuracy Score - Decision Tree: ', cv_score.mean())

dict_scores['dt'] = cv_score.mean() 

Decision Tree Classifier 

=== Results ====

Using the 70% training, 30% test split:
Accuracy score on test: 0.851764705882353
Accuracy score on train: 0.9979818365287588

=== Confusion Matrix ===
[[361  35]
 [ 28   1]]


=== Classification Report ===
              precision    recall  f1-score   support

           0       0.93      0.91      0.92       396
           1       0.03      0.03      0.03        29

    accuracy                           0.85       425
   macro avg       0.48      0.47      0.48       425
weighted avg       0.87      0.85      0.86       425



=== All AUC Scores ===
[0.64786967 0.51420217 0.70342523 0.47744361 0.58479532 0.75146199
 0.60244361 0.59868421 0.58459596 0.57323232]


=== Mean AUC Score ===
Mean AUC Score - Decision Tree:  0.6038154097364624

=== All Accuracy Scores ===
[0.92957746 0.88732394 0.93661972 0.90140845 0.88028169 0.92253521
 0.90780142 0.92198582 0.90780142 0.89361702]


=== Mean Accuracy Score ===
Mean Accuracy Score - Decision Tre

7. Decision Tree Bagging

In [17]:
#Bagging 

print('Decision Tree Bagging  \n')

# max_samples: maximum size 0.5=50% of each sample taken from the full dataset
# max_features: maximum of features 1=100% taken here all 10K 
# n_estimators: number of decision trees 
bg=BaggingClassifier(DecisionTreeClassifier(),max_samples=0.5,max_features=1.0,n_estimators=10)

bg.fit(X_train, np.ravel(y_train))

y_pred = bg.predict(X_test)

# Accuracy: 
print('=== Results ====\n')
print('Using the 70% training, 30% test split:')
print('Accuracy score on test: ' + str(bg.score(X_test, y_test)))
print('Accuracy score on train: '+ str(bg.score(X_train, y_train)))

# Using cross-validation:

cv_score = cross_val_score(bg, X, np.ravel(y), cv=10, scoring='roc_auc')

# Results AUC 

print('\n=== Confusion Matrix ===')
print(confusion_matrix(y_test, y_pred))
print('\n')
print('=== Classification Report ===')
print(classification_report(y_test, y_pred))
print('\n')
print('=== All AUC Scores ===')
print(cv_score)
print('\n')
print('=== Mean AUC Score ===')
print('Mean AUC Score - Decision Tree Bagging: ', cv_score.mean())

dict_scores_auc['bg'] = cv_score.mean() 

# Results Accuracy 
cv_score = cross_val_score(bg, X, np.ravel(y), cv=10, scoring='accuracy')

print('\n=== All Accuracy Scores ===')
print(cv_score)
print('\n')
print('=== Mean Accuracy Score ===')
print('Mean Accuracy Score - Decision Tree Bagging: ', cv_score.mean())

dict_scores['bg'] = cv_score.mean() 

Decision Tree Bagging  

=== Results ====

Using the 70% training, 30% test split:
Accuracy score on test: 0.9317647058823529
Accuracy score on train: 0.9556004036326943

=== Confusion Matrix ===
[[396   0]
 [ 29   0]]


=== Classification Report ===
              precision    recall  f1-score   support

           0       0.93      1.00      0.96       396
           1       0.00      0.00      0.00        29

    accuracy                           0.93       425
   macro avg       0.47      0.50      0.48       425
weighted avg       0.87      0.93      0.90       425



=== All AUC Scores ===
[0.87886383 0.73308271 0.76441103 0.81035923 0.74603175 0.90350877
 0.74671053 0.83505639 0.80092593 0.8030303 ]


=== Mean AUC Score ===
Mean AUC Score - Decision Tree Bagging:  0.8021980456190982


c:\users\cinti\appdata\local\programs\python\python38\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))



=== All Accuracy Scores ===
[0.94366197 0.94366197 0.92957746 0.92957746 0.92253521 0.93661972
 0.94326241 0.94326241 0.95744681 0.93617021]


=== Mean Accuracy Score ===
Mean Accuracy Score - Decision Tree Bagging:  0.9385775646788534


8. Decision Tree Adaboost 

In [18]:
# Decision Tree Adaboost 

print('Decision Tree Adaboost \n')

adb = AdaBoostClassifier(DecisionTreeClassifier(min_samples_split=10,max_depth=4),n_estimators=10,learning_rate=0.6)

adb.fit(X_train, np.ravel(y_train))

y_pred = adb.predict(X_test)

# Accuracy: 
print('=== Results ====\n')
print('Using the 70% training, 30% test split:')
print('Accuracy score on test: ' + str(adb.score(X_test, y_test)))
print('Accuracy score on train: '+ str(adb.score(X_train, y_train)))

# Using cross-validation:

cv_score = cross_val_score(adb, X, np.ravel(y), cv=10, scoring='roc_auc')

# Results AUC 

print('\n=== Confusion Matrix ===')
print(confusion_matrix(y_test, y_pred))
print('\n')
print('=== Classification Report ===')
print(classification_report(y_test, y_pred))
print('\n')
print('=== All AUC Scores ===')
print(cv_score)
print('\n')
print('=== Mean AUC Score ===')
print('Mean AUC Score - Decision Tree Adaboost: ', cv_score.mean())

dict_scores_auc['adb'] = cv_score.mean() 

# Results Accuracy 
cv_score = cross_val_score(adb, X, np.ravel(y), cv=10, scoring='accuracy')

print('\n=== All Accuracy Scores ===')
print(cv_score)
print('\n')
print('=== Mean Accuracy Score ===')
print('Mean Accuracy Score - Decision Tree Adaboost: ', cv_score.mean())

dict_scores['adb'] = cv_score.mean() 

Decision Tree Adaboost 

=== Results ====

Using the 70% training, 30% test split:
Accuracy score on test: 0.9223529411764706
Accuracy score on train: 0.9788092835519677

=== Confusion Matrix ===
[[390   6]
 [ 27   2]]


=== Classification Report ===
              precision    recall  f1-score   support

           0       0.94      0.98      0.96       396
           1       0.25      0.07      0.11        29

    accuracy                           0.92       425
   macro avg       0.59      0.53      0.53       425
weighted avg       0.89      0.92      0.90       425



=== All AUC Scores ===
[0.81328321 0.62865497 0.73809524 0.73433584 0.74352548 0.74603175
 0.83928571 0.76691729 0.59259259 0.65277778]


=== Mean AUC Score ===
Mean AUC Score - Decision Tree Adaboost:  0.7255499860763018

=== All Accuracy Scores ===
[0.91549296 0.92253521 0.95070423 0.9084507  0.8943662  0.94366197
 0.92907801 0.95744681 0.92907801 0.95035461]


=== Mean Accuracy Score ===
Mean Accuracy Score - Deci

9. Random Forest 

In [19]:
# Random Forest 

print('Random Forest \n')

rf = RandomForestClassifier()

rf.fit(X_train, np.ravel(y_train))

y_pred = rf.predict(X_test)

# Accuracy: 
print('=== Results ====\n')
print('Using the 70% training, 30% test split:')
print('Accuracy score on test: ' + str(rf.score(X_test, y_test)))
print('Accuracy score on train: '+ str(rf.score(X_train, y_train)))

# Using cross-validation:

cv_score = cross_val_score(rf, X, np.ravel(y), cv=10, scoring='roc_auc')

# Results AUC 

print('\n=== Confusion Matrix ===')
print(confusion_matrix(y_test, y_pred))
print('\n')
print('=== Classification Report ===')
print(classification_report(y_test, y_pred))
print('\n')
print('=== All AUC Scores ===')
print(cv_score)
print('\n')
print('=== Mean AUC Score ===')
print('Mean AUC Score - Random Forest: ', cv_score.mean())

dict_scores_auc['rf'] = cv_score.mean() 

# Results Accuracy 
cv_score = cross_val_score(rf, X, np.ravel(y), cv=10, scoring='accuracy')

print('\n=== All Accuracy Scores ===')
print(cv_score)
print('\n')
print('=== Mean Accuracy Score ===')
print('Mean Accuracy Score - Random Forest: ', cv_score.mean())

dict_scores['rf'] = cv_score.mean() 

Random Forest 

=== Results ====

Using the 70% training, 30% test split:
Accuracy score on test: 0.9294117647058824
Accuracy score on train: 0.9969727547931383

=== Confusion Matrix ===
[[395   1]
 [ 29   0]]


=== Classification Report ===
              precision    recall  f1-score   support

           0       0.93      1.00      0.96       396
           1       0.00      0.00      0.00        29

    accuracy                           0.93       425
   macro avg       0.47      0.50      0.48       425
weighted avg       0.87      0.93      0.90       425



=== All AUC Scores ===
[0.85004177 0.8091061  0.8015873  0.79573935 0.91896408 0.92021721
 0.86090226 0.94736842 0.9212963  0.84006734]


=== Mean AUC Score ===
Mean AUC Score - Random Forest:  0.8665290119237488

=== All Accuracy Scores ===
[0.94366197 0.94366197 0.96478873 0.92957746 0.94366197 0.95070423
 0.94326241 0.95035461 0.94326241 0.94326241]


=== Mean Accuracy Score ===
Mean Accuracy Score - Random Forest:  0.9456

10. Voting Classifier

In [20]:
# Voting Classification 

print('Voting Classification \n')

vc=VotingClassifier(estimators=[('mnb',mnb),('lr',lr),('rf',rf),('svm',svm_linear)],voting='hard')
vc.fit(X_train, np.ravel(y_train))

y_pred = vc.predict(X_test)

# Accuracy: 
print('=== Results ====\n')
print('Using the 70% training, 30% test split:')
print('Accuracy score on test: ' + str(vc.score(X_test, y_test)))
print('Accuracy score on train: '+ str(vc.score(X_train, y_train)))

dict_scores['vc'] = vc.score(X_test, y_test)

Voting Classification 



c:\users\cinti\appdata\local\programs\python\python38\lib\site-packages\sklearn\linear_model\_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=2):
ABNORMAL_TERMINATION_IN_LNSRCH.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


=== Results ====

Using the 70% training, 30% test split:
Accuracy score on test: 0.9294117647058824
Accuracy score on train: 0.9424823410696267


In [21]:
print(dict_scores)

{'gnb': 0.9350214763759863, 'mbn': 0.8799320747178104, 'lg': 0.9378583558086107, 'knn': 0.9378583558086107, 'sgd': 0.7632104684846668, 'svm_linear': 0.9378583558086107, 'svm_poly': 0.9399810208770353, 'svm_quadratic': 0.9371491359504546, 'svm_RBF': 0.9378583558086107, 'dt': 0.9088952152632105, 'bg': 0.9385775646788534, 'adb': 0.9301168714414144, 'rf': 0.9456198181999801, 'vc': 0.9294117647058824}


In [22]:
print(dict_scores_auc)

{'gnb': 0.7035831371357687, 'mnb': 0.5910135186450975, 'lr': 0.5, 'knn': 0.7280007151717678, 'sgd': 0.3229405584668742, 'svm_linear': 0.546542809042809, 'svm_poly': 0.6407926381610592, 'svm_quadratic': 0.566839447102605, 'svm_rbf': 0.7691118579276475, 'dt': 0.6038154097364624, 'bg': 0.8021980456190982, 'adb': 0.7255499860763018, 'rf': 0.8665290119237488}


Considering both Accuracy and AUC curve, Random Forest performs best in our dataset.

In [23]:
print(rf.get_params())

{'bootstrap': True, 'ccp_alpha': 0.0, 'class_weight': None, 'criterion': 'gini', 'max_depth': None, 'max_features': 'auto', 'max_leaf_nodes': None, 'max_samples': None, 'min_impurity_decrease': 0.0, 'min_impurity_split': None, 'min_samples_leaf': 1, 'min_samples_split': 2, 'min_weight_fraction_leaf': 0.0, 'n_estimators': 100, 'n_jobs': None, 'oob_score': False, 'random_state': None, 'verbose': 0, 'warm_start': False}


In [24]:
# Tunning Parameters 

# Number of trees in random forest
n_estimators = [int(x) for x in np.linspace(start = 200, stop = 2000, num = 10)]
# Number of features to consider at every split
max_features = ['auto', 'sqrt', 'log2']
# Maximum number of levels in tree
max_depth = [int(x) for x in np.linspace(10, 110, num = 11)]
max_depth.append(None)
# Minimum number of samples required to split a node
min_samples_split = [2, 5, 10]
# Minimum number of samples required at each leaf node
min_samples_leaf = [1, 2, 4]
# Method of selecting samples for training each tree
bootstrap = [True, False]
# Create the random grid
random_grid = {'n_estimators': n_estimators,
               'max_features': max_features,
               'max_depth': max_depth,
               'min_samples_split': min_samples_split,
               'min_samples_leaf': min_samples_leaf,
               'bootstrap': bootstrap}

In [25]:
print(random_grid)

{'n_estimators': [200, 400, 600, 800, 1000, 1200, 1400, 1600, 1800, 2000], 'max_features': ['auto', 'sqrt', 'log2'], 'max_depth': [10, 20, 30, 40, 50, 60, 70, 80, 90, 100, 110, None], 'min_samples_split': [2, 5, 10], 'min_samples_leaf': [1, 2, 4], 'bootstrap': [True, False]}


In [26]:
# Base model to tune

rf = RandomForestRegressor()

# Random search of parameters, using 3 fold cross validation, search across 100 different combinations, 
# and use all available cores

rf_random = RandomizedSearchCV(estimator = rf, 
                               param_distributions = random_grid, 
                               n_iter = 100, 
                               cv = 3, 
                               verbose=2, 
                               random_state=42, 
                               n_jobs = -1)

# Fit the random search model

rf_random.fit(X_train, y_train)

rf_random.best_params_

Fitting 3 folds for each of 100 candidates, totalling 300 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done  25 tasks      | elapsed:   37.4s
[Parallel(n_jobs=-1)]: Done 146 tasks      | elapsed:  3.4min
[Parallel(n_jobs=-1)]: Done 300 out of 300 | elapsed:  7.2min finished
c:\users\cinti\appdata\local\programs\python\python38\lib\site-packages\sklearn\model_selection\_search.py:765: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  self.best_estimator_.fit(X, y, **fit_params)


{'n_estimators': 400,
 'min_samples_split': 2,
 'min_samples_leaf': 4,
 'max_features': 'log2',
 'max_depth': 80,
 'bootstrap': True}

In [27]:
# Random Forest with best parameters 

print('Random Forest \n')

rf = RandomForestClassifier(n_estimators= 600,
                            min_samples_split= 10,
                            min_samples_leaf= 4,
                            max_features= 'sqrt',
                            max_depth= 40,
                            bootstrap= True)

rf.fit(X_train, np.ravel(y_train))

y_pred = rf.predict(X_test)

# Accuracy: 
print('=== Results ====\n')
print('Using the 70% training, 30% test split:')
print('Accuracy score on test: ' + str(rf.score(X_test, y_test)))
print('Accuracy score on train: '+ str(rf.score(X_train, y_train)))

# Using cross-validation:

cv_score = cross_val_score(rf, X, np.ravel(y), cv=10, scoring='roc_auc')

# Results AUC 

print('\n=== Confusion Matrix ===')
print(confusion_matrix(y_test, y_pred))
print('\n')
print('=== Classification Report ===')
print(classification_report(y_test, y_pred))
print('\n')
print('=== All AUC Scores ===')
print(cv_score)
print('\n')
print('=== Mean AUC Score ===')
print('Mean AUC Score - Random Forest: ', cv_score.mean())

dict_scores_auc['rf'] = cv_score.mean() 

# Results Accuracy 
cv_score = cross_val_score(rf, X, np.ravel(y), cv=10, scoring='accuracy')

print('\n=== All Accuracy Scores ===')
print(cv_score)
print('\n')
print('=== Mean Accuracy Score ===')
print('Mean Accuracy Score - Random Forest: ', cv_score.mean())

dict_scores['rf'] = cv_score.mean() 

Random Forest 

=== Results ====

Using the 70% training, 30% test split:
Accuracy score on test: 0.9317647058823529
Accuracy score on train: 0.9404641775983855

=== Confusion Matrix ===
[[396   0]
 [ 29   0]]


=== Classification Report ===
              precision    recall  f1-score   support

           0       0.93      1.00      0.96       396
           1       0.00      0.00      0.00        29

    accuracy                           0.93       425
   macro avg       0.47      0.50      0.48       425
weighted avg       0.87      0.93      0.90       425



=== All AUC Scores ===
[0.82038429 0.81787803 0.75898079 0.89139515 0.87969925 0.92314119
 0.86184211 0.94736842 0.93602694 0.8543771 ]


=== Mean AUC Score ===
Mean AUC Score - Random Forest:  0.8691093263461683


c:\users\cinti\appdata\local\programs\python\python38\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))



=== All Accuracy Scores ===
[0.94366197 0.93661972 0.94366197 0.93661972 0.93661972 0.93661972
 0.94326241 0.94326241 0.94326241 0.94326241]


=== Mean Accuracy Score ===
Mean Accuracy Score - Random Forest:  0.9406852462291481


In [28]:
from sklearn.model_selection import GridSearchCV
# Create the parameter grid based on the results of random search 
param_grid = {
    'bootstrap': [True],
    'max_depth': [80, 90, 100, 110],
    'max_features': [2, 3],
    'min_samples_leaf': [3, 4, 5],
    'min_samples_split': [8, 10, 12],
    'n_estimators': [100, 200, 300, 1000]
}
# Create a based model
rf = RandomForestRegressor()
# Instantiate the grid search model
grid_search = GridSearchCV(estimator = rf, param_grid = param_grid, 
                          cv = 3, n_jobs = -1, verbose = 2)


# Fit the grid search to the data
grid_search.fit(X_train, y_train)
print(grid_search.best_params_)
best_grid = grid_search.best_estimator_
print(best_grid)

Fitting 3 folds for each of 288 candidates, totalling 864 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done  25 tasks      | elapsed:    7.8s
[Parallel(n_jobs=-1)]: Done 146 tasks      | elapsed:   55.9s
[Parallel(n_jobs=-1)]: Done 349 tasks      | elapsed:  2.3min
[Parallel(n_jobs=-1)]: Done 632 tasks      | elapsed:  4.2min
[Parallel(n_jobs=-1)]: Done 864 out of 864 | elapsed:  5.8min finished
c:\users\cinti\appdata\local\programs\python\python38\lib\site-packages\sklearn\model_selection\_search.py:765: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  self.best_estimator_.fit(X, y, **fit_params)


{'bootstrap': True, 'max_depth': 80, 'max_features': 2, 'min_samples_leaf': 5, 'min_samples_split': 8, 'n_estimators': 100}
RandomForestRegressor(max_depth=80, max_features=2, min_samples_leaf=5,
                      min_samples_split=8)


In [29]:
# Random Forest with best parameters 

print('Random Forest \n')

rf = RandomForestClassifier(n_estimators= 100,
                            min_samples_split= 12,
                            min_samples_leaf= 4,
                            max_features= 2,
                            max_depth= 100,
                            bootstrap= True)

rf.fit(X_train, np.ravel(y_train))

y_pred = rf.predict(X_test)

# Accuracy: 
print('=== Results ====\n')
print('Using the 70% training, 30% test split:')
print('Accuracy score on test: ' + str(rf.score(X_test, y_test)))
print('Accuracy score on train: '+ str(rf.score(X_train, y_train)))

# Using cross-validation:

cv_score = cross_val_score(rf, X, np.ravel(y), cv=10, scoring='roc_auc')

# Results AUC 

print('\n=== Confusion Matrix ===')
print(confusion_matrix(y_test, y_pred))
print('\n')
print('=== Classification Report ===')
print(classification_report(y_test, y_pred))
print('\n')
print('=== All AUC Scores ===')
print(cv_score)
print('\n')
print('=== Mean AUC Score ===')
print('Mean AUC Score - Random Forest: ', cv_score.mean())

dict_scores_auc['rf'] = cv_score.mean() 

# Results Accuracy 
cv_score = cross_val_score(rf, X, np.ravel(y), cv=10, scoring='accuracy')

print('\n=== All Accuracy Scores ===')
print(cv_score)
print('\n')
print('=== Mean Accuracy Score ===')
print('Mean Accuracy Score - Random Forest: ', cv_score.mean())

dict_scores['rf'] = cv_score.mean() 

Random Forest 

=== Results ====

Using the 70% training, 30% test split:
Accuracy score on test: 0.9317647058823529
Accuracy score on train: 0.9404641775983855

=== Confusion Matrix ===
[[396   0]
 [ 29   0]]


=== Classification Report ===
              precision    recall  f1-score   support

           0       0.93      1.00      0.96       396
           1       0.00      0.00      0.00        29

    accuracy                           0.93       425
   macro avg       0.47      0.50      0.48       425
weighted avg       0.87      0.93      0.90       425



=== All AUC Scores ===
[0.83082707 0.80033417 0.77401838 0.89223058 0.8780284  0.93984962
 0.85526316 0.93796992 0.92171717 0.81481481]


=== Mean AUC Score ===
Mean AUC Score - Random Forest:  0.8645053289790132


c:\users\cinti\appdata\local\programs\python\python38\lib\site-packages\sklearn\metrics\_classification.py:1221: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))



=== All Accuracy Scores ===
[0.94366197 0.93661972 0.93661972 0.93661972 0.93661972 0.94366197
 0.94326241 0.94326241 0.94326241 0.93617021]


=== Mean Accuracy Score ===
Mean Accuracy Score - Random Forest:  0.9399760263709919


In [ ]:
# Tunning Parameters 

# Number of trees in random forest
n_estimators = [int(x) for x in np.linspace(start = 200, stop = 2000, num = 10)]
# Number of features to consider at every split
max_features = ['auto', 'sqrt', 'log2']
# Maximum number of levels in tree
max_depth = [int(x) for x in np.linspace(10, 110, num = 11)]
max_depth.append(None)
# Minimum number of samples required to split a node
min_samples_split = [2, 5, 10]
# Minimum number of samples required at each leaf node
min_samples_leaf = [1, 2, 4]
# Method of selecting samples for training each tree
bootstrap = [True, False]
# Create the random grid
random_grid = {'n_estimators': n_estimators,
               'max_features': max_features,
               'max_depth': max_depth,
               'min_samples_split': min_samples_split,
               'min_samples_leaf': min_samples_leaf,
               'bootstrap': bootstrap}

# Create the parameter grid based on the results of random search 
param_grid = {'n_estimators': n_estimators,
               'max_features': max_features,
               'max_depth': max_depth,
               'min_samples_split': min_samples_split,
               'min_samples_leaf': min_samples_leaf,
               'bootstrap': bootstrap}
   
# Create a based model
rf = RandomForestRegressor()
# Instantiate the grid search model
grid_search = GridSearchCV(estimator = rf, param_grid = param_grid, 
                          cv = 3, n_jobs = -1, verbose = 2)


# Fit the grid search to the data
grid_search.fit(X_train, y_train)
print(grid_search.best_params_)
best_grid = grid_search.best_estimator_
print(best_grid)


Fitting 3 folds for each of 6480 candidates, totalling 19440 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 8 concurrent workers.
[Parallel(n_jobs=-1)]: Done  25 tasks      | elapsed:   38.6s
[Parallel(n_jobs=-1)]: Done 146 tasks      | elapsed:  4.6min
[Parallel(n_jobs=-1)]: Done 349 tasks      | elapsed: 10.4min
[Parallel(n_jobs=-1)]: Done 632 tasks      | elapsed: 15.9min
[Parallel(n_jobs=-1)]: Done 997 tasks      | elapsed: 25.8min
[Parallel(n_jobs=-1)]: Done 1442 tasks      | elapsed: 35.2min
[Parallel(n_jobs=-1)]: Done 1969 tasks      | elapsed: 48.5min
[Parallel(n_jobs=-1)]: Done 2576 tasks      | elapsed: 60.2min
[Parallel(n_jobs=-1)]: Done 3265 tasks      | elapsed: 72.7min
[Parallel(n_jobs=-1)]: Done 4034 tasks      | elapsed: 87.9min
[Parallel(n_jobs=-1)]: Done 4885 tasks      | elapsed: 105.8min
[Parallel(n_jobs=-1)]: Done 5816 tasks      | elapsed: 126.2min
